### ISSUE TITLE
Translate some words

### ISSUE THREAD

**Issue by savionascimentodev** [vuejs-translations/docs-pt#143]
Hello friends, I'm opening an issue, to discuss some words, I'll suggest some here, please comment what you think, we'll try to make it better for everyone!

Some examples here:

'abstração' -> 'estrutura'
'equipa' -> 'equipe' || 'time'
'interpretação' -> 'renderização' (depending on the context)
'gatilhos' -> 'ganchos'

- In Brazilians we find the feminine article very strange and unusual, before like 'a Vue' it would be better 'o Vue' how could we make it better for us, my friends? Just put 'vue', maybe?
- I saw the previous conversation, and I think the best thing would be to translate it to 'documento' then.
- I think some words don't need 100% translation like:
   - 'corrêio eletrônico' -> email

These are small improvements, which I brought to discuss with you, I hope they help all Brazilians and non-Brazilians, please comment what you think, we can help each other!

Obs: If I see more words I will update this issue to always seek the best for our project, if you agree of course.

@viniciusdeliz @nazarepiedady

**Comment by viniciusdeliz** [comment]
A suggestion to make this work would be a glossary, or even a "live" glossary, maybe? We could choose the more universal terms based on user votes in this live glossary perhaps? 

Some inspiration from the [World Wide Web Consortium (W3C) documentation: French glossary](https://github.com/w3c/translation-glossaries/blob/main/fran%C3%A7ais-French.md)

**Comment by nazarepiedady** [comment]
I recommend not wasting your time on this because it won't be changed any time soon, as I have every intention of keeping the language as grammatically standardised and less informal as possible.

Just as I've said many times that the same subject has been raised, I'll say it again, dictionaries aren't written for nothing, they're for consulting every time you come across words you don't know.

The terms and words I used when I started translating are present in all variants of our language, only many of them are words and terms that aren't used very often.

It's normal not to be familiar with everything when we're dealing with things that are outside our everyday lives, so we shouldn't expect to be familiar with every term and word we come across.

I use a dictionary every time I come across a word in material written by Brazilians, it costs nothing to learn how to use it.

As for the gender of the words, I translate the word **framework** as **abstração** because even in English they are described as **abstractions** in academic computing materials written in English and by our English-speaking colleagues with more than 20 years' experience.

**Vue** described as **uma estrutura**, **uma abstração**, or **uma ferramenta**, is still "uma" and not "um".

**You only need to use the Portuguese dictionary when you come across an unfamiliar word, even though there aren't that many, it's very simple, not that difficult, and it's not too much to ask.**

@viniciusdeliz, @savionascimentodev

**Comment by savionascimentodev** [comment]
Okay then, you can close this issue @nazarepiedady 😀

**Comment by nazarepiedady** [comment]
@savionascimentodev, you can translate using whatever terms and words you like, because once I've approved the request to update the repository, I'll edit anything that doesn't conform to the previously established standards.

You don't have to use the words I've recommended if you don't want to, because I'll edit them later.

And by the way, **renderizar**, **renderização** and **renderizado** are not Portuguese. The English verb **to render** translates intelligibly as **gerar**, **desenhar**, **produzir**, and **interpretar**. For example, when in English we say **to render a 3D model**, in Portuguese we can say, **produzir um modelo em três dimensões**.

**Comment by viniciusdeliz** [comment]
@nazarepiedady Intransigence and the unwillingness to discuss common pain points for users and collaborators of the documentation only screams insecurity, stiffness and power trips. It's extremely rude to infer that collaborators or users do not know or can't use dictionaries just because they think a word is not proper in a certain context.

**Comment by viniciusdeliz** [comment]
> @savionascimentodev, you can translate using whatever terms and words you like, because once I've approved the request to update the repository, I'll edit anything that doesn't conform to the previously established standards.
> 
> You don't have to use the words I've recommended if you don't want to, because I'll edit them later.
> 
> And by the way, **renderizar**, **renderização** and **renderizado** are not Portuguese. The English verb **to render** translates intelligibly as **gerar**, **desenhar**, **produzir**, and **interpretar**. For example, when in English we say **to render a 3D model**, in Portuguese we can say, **produzir um modelo em três dimensões**.


I do not want to bring up the `render` and `interpretar` debate, but just so you can see that there are many live and rightful points of views: Porto Editora, based in Portugal, disagrees with your message: https://www.infopedia.pt/apoio/artigos/$graficos-3-d

**Comment by savionascimentodev** [comment]
My friends, whatever you decide for me is ok, I just want to help, you have been here longer, there is no problem for me, no one is being rude 😄

**Comment by nazarepiedady** [comment]
@viniciusdeliz, I only see some brazilians complaining about those words and see that there are a lot of brazilians that can easily read this documentation, so what these did that others can do.

Why is it a pain?
It is Portuguese.

I said before, just use the dictionaries, we are not reading stories book here, we are at scientific environment, science differ from our day to day lives, we will learn new words even on the content that we are accustomed.

Also, we could code a tooltip component that could should another form of the word when the user hover it, what you think about this point?

**Comment by nazarepiedady** [comment]
@viniciusdeliz, I created a new issue assigned to you. Give me your feedback 😀. 

We need to find a solution here.

**Comment by viniciusdeliz** [comment]
The verb "Renderizar" is not a loanword by the way, it's a [neologism](https://en.wikipedia.org/wiki/Neologism).

**Comment by nazarepiedady** [comment]
@viniciusdeliz, I will use the word “desenhar” in many places where I use “interpretar” because it communicates better the desired meaning.
