### ISSUE TITLE
docs(pt): translate `style-guide/rules-essential.md`

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#45]
A tradução deste documento está sobre a responsabilidade do @nazarepiedady

**Comment by nazarepiedady** [comment]
Agora, a tradução deste documento está sobre a responsabilidade do @mumumilk.

@mumumilk atualize a tua bifurcação (conhecido como **fork**) local antes de começares a traduzir este documento.

Nós estamos a caminhar muito bem, teremos tudo terminado ainda antes de Dezembro, contando com a fase de revisão.

**Comment by viniciusdeliz** [comment]
please confirm if you're available to tackle this one as well @mumumilk

**Comment by mumumilk** [comment]
yep im on it

**Comment by nazarepiedady** [comment]
@viniciusdeliz, in case this file is not translated until the middle of the next month,
could you take it to translate it yourself?

**Comment by viniciusdeliz** [comment]
@mumumilk let me know if I can grab this one

**Comment by mumumilk** [comment]
sure thing, go ahead... Sorry i didn't had the time lately to address this

**Comment by mumumilk** [comment]
And just FYI, i think a lot of what we already have in the vue 2 docs in portuguese can be reused here as well 

Example:
https://br.vuejs.org/v2/style-guide/index.html#Prioridade-B-Altamente-Recomendado

**Comment by viniciusdeliz** [comment]
@mumumilk no need to be sorry! I thank you for all the effort and contribution.
There's also a [file in the former Vue3 docs](https://github.com/vuejs-br/docs-next/tree/master/src/style-guide) which can be used.  Coincidentally, I'm the one who translated it more than two years ago. It was a huge effort because all the "Recommended" sections were in a single file :rofl: https://github.com/vuejs-br/docs-next/commit/831cbcf4687e28071adec8dad199b4baf6df220c
